input_string = input()
result =input_string.replace("c=","1")
result = result.replace("c-","1")
result = result.replace("dz=","1")
result = result.replace("d-","1")
result = result.replace("lj","1")
result = result.replace("nj","1")
result = result.replace("s=","1")
result = result.replace("z=","1")
print(len(result))